import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './int2-ihm-tests',
  testMatch: ['**/int2-ihm-pages-autogenerated.spec.ts'],
  timeout: 180000,
  fullyParallel: false,
  workers: 1,
  outputDir: 'int2-ihm-test-results/chains',
  use: {
    headless: false,
    screenshot: 'on',
    trace: 'on',
    video: 'on',
    ignoreHTTPSErrors: true,
    launchOptions: {
      slowMo: 350,
    },
  },
  reporter: [['html', { open: 'never' }], ['list']],
});