import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './int2-ihm-tests',
  testMatch: [
    '**/int2-ihm-pages-autogenerated.spec.ts',
    '**/int2-ihm-create-workflows-autonomous.spec.ts',
  ],
  timeout: 180000,
  fullyParallel: false,
  workers: 1,
  outputDir: 'int2-ihm-test-results/exhaustive',
  use: {
    baseURL: 'https://orion-int2.itsap.net',
    headless: false,
    screenshot: 'on',
    trace: 'on',
    video: 'on',
    ignoreHTTPSErrors: true,
    launchOptions: {
      slowMo: 400,
    },
  },
  reporter: [['html', { open: 'never' }], ['list']],
});